import Foundation

/// Phase V.5d — pure-data badge descriptor for `AuthorshipTag`.
///
/// The contract this file enforces:
///
/// 1. **Total over `AuthorshipTag?`.** `descriptor(for:context:)`
///    handles every case of `AuthorshipTag?` plus a `BadgeContext`
///    that distinguishes legacy NULL on a tracked surface (KB) from
///    a surface that does not yet carry the column at all (timeline,
///    skills). Switch is exhaustive — adding a new tag forces a
///    compile error here.
///
/// 2. **No inference.** `.unset` and `.none` (legacy NULL) both
///    render as a subdued "Untagged" affordance — never silently
///    relabelled to AI / Human / Mixed. Cavoukian red flag holds.
///
/// 3. **Copy + tone live here.** Tooltips and labels are static
///    constants so the SwiftUI host (`AuthorshipBadgeView`) and any
///    future TUI / web surface render the same words; tests can
///    lock the rules without touching SwiftUI.
public enum AuthorshipBadge {

    /// Visual weight tier. The view layer maps this to opacity /
    /// color — Core stays free of SwiftUI types so the rules are
    /// unit-testable.
    public enum Weight: String, Sendable, Equatable {
        /// One of the three explicit tags. Render at full visual weight.
        case explicit
        /// `.unset` on a tracked surface (KB row written via the
        /// V.5 path that has not been resolved yet). Subdued, with
        /// a tooltip nudging the operator to resolve via the prompt.
        case unset
        /// Legacy NULL on a tracked surface (KB row predating V.5).
        /// Subdued, tooltip mentions backfill (`senkani authorship
        /// backfill`).
        case legacy
        /// The surface does not yet carry the authorship column at
        /// all (token_events on the timeline, filesystem-scanned
        /// skills). Subdued, tooltip explains why.
        case untracked
    }

    /// Source surface the badge renders on. Drives which tooltip
    /// the `untagged` states show — V.5 covers KB; the other two
    /// surfaces don't carry the column yet.
    public enum BadgeContext: String, Sendable, Equatable {
        /// KB entity row / detail. Authorship is a real column.
        case knowledgeBase
        /// AgentTimelinePane row. token_events does not carry
        /// authorship in V.5; everything reads as `.untracked`.
        case timeline
        /// SkillBrowserView row / detail. Skills are scanned from
        /// the filesystem; no DB authorship column.
        case skills
    }

    /// Pure-data render descriptor. The view layer reads `label`
    /// + `weight` and uses `tooltip` for hover help.
    public struct Descriptor: Sendable, Equatable {
        public let label: String
        public let weight: Weight
        public let tooltip: String

        public init(label: String, weight: Weight, tooltip: String) {
            self.label = label
            self.weight = weight
            self.tooltip = tooltip
        }
    }

    // MARK: - Tooltip copy (Podmajersky-aligned, V.5d)

    /// Tooltip on an `.aiAuthored` badge.
    public static let aiTooltip =
        "Generated by an AI agent without operator edits."

    /// Tooltip on a `.humanAuthored` badge.
    public static let humanTooltip =
        "Authored by a human; AI may have suggested but you produced the canonical text."

    /// Tooltip on a `.mixed` badge.
    public static let mixedTooltip =
        "Co-authored — AI output merged with operator edits."

    /// Tooltip on `.unset` rows in the KB (operator owes a decision).
    public static let unsetTooltipKB =
        "You haven't tagged this entry yet. The save prompt will ask before the next save."

    /// Tooltip on legacy NULL rows in the KB (predates V.5).
    public static let legacyTooltipKB =
        "Legacy entry from before authorship tracking. Run `senkani authorship backfill` to tag old rows."

    /// Tooltip on timeline rows — the column does not exist there.
    public static let untrackedTooltipTimeline =
        "Token events don't carry authorship; tagging covers Knowledge Base entries today."

    /// Tooltip on skill rows — skills are filesystem-scanned, no DB column.
    public static let untrackedTooltipSkills =
        "Skills are scanned from disk; authorship tagging covers Knowledge Base entries today."

    // MARK: - Resolver

    /// Build the badge descriptor for a tag (or absence) on a given
    /// surface. `tag == nil` means the underlying row's column is
    /// NULL (legacy KB row) OR the surface does not carry the
    /// column at all (timeline, skills) — `context` disambiguates.
    public static func descriptor(
        for tag: AuthorshipTag?,
        context: BadgeContext
    ) -> Descriptor {
        switch tag {
        case .some(.aiAuthored):
            return Descriptor(label: AuthorshipTag.aiAuthored.displayLabel,
                              weight: .explicit, tooltip: aiTooltip)
        case .some(.humanAuthored):
            return Descriptor(label: AuthorshipTag.humanAuthored.displayLabel,
                              weight: .explicit, tooltip: humanTooltip)
        case .some(.mixed):
            return Descriptor(label: AuthorshipTag.mixed.displayLabel,
                              weight: .explicit, tooltip: mixedTooltip)
        case .some(.unset):
            return Descriptor(label: AuthorshipTag.unset.displayLabel,
                              weight: .unset, tooltip: unsetTooltipKB)
        case .none:
            switch context {
            case .knowledgeBase:
                return Descriptor(label: AuthorshipTag.unset.displayLabel,
                                  weight: .legacy, tooltip: legacyTooltipKB)
            case .timeline:
                return Descriptor(label: AuthorshipTag.unset.displayLabel,
                                  weight: .untracked, tooltip: untrackedTooltipTimeline)
            case .skills:
                return Descriptor(label: AuthorshipTag.unset.displayLabel,
                                  weight: .untracked, tooltip: untrackedTooltipSkills)
            }
        }
    }
}
