import Foundation

/// Provenance metadata for an artifact row (KB entity, learned rule,
/// skill, etc.). Phase V.5 — see `spec/roadmap.md` row "V.5 —
/// `AuthorshipTracker`" and the synthesis red flag from Gebru:
/// silent inference of authorship rewrites history. The enum is
/// **explicit by construction**: callers pass one of these four
/// values at write time. NULL in the underlying column means
/// "legacy row, never written through the tagged path"; it is NOT
/// silently equivalent to `.humanAuthored`.
///
/// The string values are stable on disk — round-trip through SQLite
/// goes through `rawValue` so any rename here is a schema break.
public enum AuthorshipTag: String, Sendable, Codable, Equatable, CaseIterable {
    /// Generated by an AI agent without operator edits.
    case aiAuthored = "ai-authored"
    /// Authored by a human; AI may have suggested but the operator
    /// produced the canonical text.
    case humanAuthored = "human-authored"
    /// Co-authored — neither side is dominant. Use this when the
    /// operator merged AI output with their own edits.
    case mixed
    /// Operator has not yet chosen. The save path MUST prompt
    /// before this row participates in any policy decision (V.5b).
    /// This value is the explicit "I don't know yet" state — never
    /// silently inferred to mean any of the other three.
    case unset
}

public extension AuthorshipTag {
    /// Human-readable label for UI rendering. Pure data — no
    /// inference, no policy. UI badges read from here.
    var displayLabel: String {
        switch self {
        case .aiAuthored:    return "AI"
        case .humanAuthored: return "Human"
        case .mixed:         return "Mixed"
        case .unset:         return "Untagged"
        }
    }

    /// True for the three "tagged" states; false only for `.unset`.
    /// Callers that gate on "must be explicitly tagged" should
    /// check this before performing the operation. Code paths that
    /// silently treat `.unset` as `.humanAuthored` (or anything
    /// else) violate the V.5 contract.
    var isExplicit: Bool { self != .unset }
}
