import Foundation

// MARK: - ContextSignalGenerator
//
// Phase H+2b: turns recurring file-path mentions (SQL-detected) into
// `LearnedContextDoc` proposals. Deterministic — no LLM. The body
// describes the observation, not the file's contents. (Future round
// can enrich the body with Gemma via the same `RationaleLLM`
// infrastructure as H+2a.)
//
// Why we don't read file content:
//   - The body is SecretDetector-scanned but cheap bodies stay cheap
//     when we never pull raw source into them.
//   - File content changes across sessions — the proposal needs to
//     stay valid against evolving code.
//   - Karpathy: eval surface shrinks dramatically when the generator
//     doesn't speculate about file contents.
//
// The ORIGINAL mention count drives confidence (Laplace-smoothed the
// same way Phase K's filter-rule confidence is).
//
// Safety:
//   - Body ≤ 2 KB, SecretDetector.scan enforced (via LearnedContextDoc
//     init/decode sanitizers).
//   - Title slug is filesystem-safe (sanitizer in LearnedContextDoc).
//   - Path length capped at 160 chars for display.

public enum ContextSignalGenerator {

    /// Analyze a project for recurring file-path mentions and produce
    /// context-doc proposals. Returns one `LearnedContextDoc` per row
    /// above the threshold, in stable id-determined order.
    public static func analyze(
        projectRoot: String,
        sessionId: String,
        db: SessionDatabase,
        minSessions: Int = 3,
        limit: Int = 10,
        now: Date = Date()
    ) -> [LearnedContextDoc] {
        let rows = db.recurringFileMentions(
            projectRoot: projectRoot,
            minSessions: minSessions,
            limit: limit
        )
        guard !rows.isEmpty else { return [] }

        return rows.map { row in
            let displayPath = String(row.path.prefix(160))
            let title = Self.titleForPath(row.path)
            let body = Self.buildBody(
                path: displayPath,
                sessions: row.sessionCount,
                mentions: row.mentionCount
            )
            let confidence = ConfidenceEstimator.laplace(
                avgSavedPct: 0,  // we're not gating on savings — this is recall
                sessionCount: row.sessionCount
            )
            // `avgSavedPct=0` under Laplace gives a high confidence
            // score (interpreting "unfiltered"); for context signals
            // we want the same shape — "high session count → high
            // confidence this is load-bearing."
            return LearnedContextDoc(
                id: UUID().uuidString,
                title: title,
                body: body,
                sources: [sessionId],
                confidence: confidence,
                status: .recurring,
                createdAt: now,
                lastSeenAt: now,
                recurrenceCount: 1,
                sessionCount: row.sessionCount
            )
        }
    }

    // MARK: - Helpers

    /// Slug from a file path. `Sources/Core/FilterPipeline.swift`
    /// becomes `sources-core-filterpipeline-swift`. Length-capped by
    /// `LearnedContextDoc.sanitizeTitle`.
    static func titleForPath(_ path: String) -> String {
        // Prefer the last two path components — more distinctive than
        // just the filename (which would collide on common names like
        // `tests.swift`, `index.ts`).
        let parts = path.split(separator: "/").suffix(2).joined(separator: "-")
        return LearnedContextDoc.sanitizeTitle(parts.isEmpty ? path : parts)
    }

    /// Deterministic markdown body — describes the observation without
    /// speculating about the file's contents. Operator/LLM can enrich
    /// later via the KB enrichment pipeline.
    static func buildBody(path: String, sessions: Int, mentions: Int) -> String {
        """
        # \(path)

        This file recurs across **\(sessions) distinct sessions** (\(mentions) total mentions). \
        The agent returns to it often enough that surfacing its role at session start \
        pays off more than re-discovering it each time.

        _Generated by senkani's context-signal detector. Edit this file to add project-specific context — your edits persist across enrichment rounds._
        """
    }
}
