import Foundation

/// Table-driven diagnostic rewriter.
/// Transforms raw validator output into agent-friendly advisories.
/// Each advisory tells the agent what to DO, not just what's wrong.
public enum DiagnosticRewriter {

    /// Maximum diagnostics per advisory (avoid noise).
    private static let maxDiagnostics = 5

    /// Rewrite raw validator output into an agent-facing advisory.
    /// Returns empty string if output indicates success (no errors).
    public static func rewrite(rawOutput: String, validatorName: String, filePath: String) -> String {
        let lines = rawOutput.components(separatedBy: .newlines)
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }

        guard !lines.isEmpty else { return "" }

        var diagnostics: [String] = []

        for line in lines {
            // Skip note/warning context lines (keep only errors)
            let lower = line.lowercased()
            if lower.contains("note:") || lower.hasPrefix("^") || lower.hasPrefix("~") { continue }
            if lower.hasPrefix("in file included") || lower.hasPrefix("generated by") { continue }

            if let rewritten = rewriteLine(line, validatorName: validatorName) {
                diagnostics.append(rewritten)
            }
        }

        guard !diagnostics.isEmpty else { return "" }

        let shown = Array(diagnostics.prefix(maxDiagnostics))
        var result = shown.joined(separator: "\n")

        if diagnostics.count > maxDiagnostics {
            result += "\n... and \(diagnostics.count - maxDiagnostics) more issues. Run senkani_validate for full output."
        }

        return result
    }

    // MARK: - Line Rewriting

    private static func rewriteLine(_ line: String, validatorName: String) -> String? {
        // Try each pattern set
        for (check, transform) in rewriteRules {
            if let result = check(line) {
                return transform(result) + " Re-save to re-validate."
            }
        }

        // Fallback: strip validator prefix, keep the diagnostic
        let cleaned = stripValidatorPrefix(line)
        guard !cleaned.isEmpty else { return nil }
        // Skip lines that are just file paths or numbers
        if cleaned.allSatisfy({ $0.isNumber || $0 == ":" || $0 == "/" || $0 == "." }) { return nil }
        return cleaned + " Re-save to re-validate."
    }

    private static func stripValidatorPrefix(_ line: String) -> String {
        // Strip common prefixes like "error:", "Error:", validator names, etc.
        var s = line
        for prefix in ["error: ", "Error: ", "ERROR: ", "warning: ", "Warning: "] {
            if s.hasPrefix(prefix) { s = String(s.dropFirst(prefix.count)); break }
        }
        return s
    }

    // MARK: - Pattern Rules

    /// Each rule is a (check, transform) pair.
    /// check: returns extracted components if the line matches, nil otherwise.
    /// transform: converts the components into an agent-friendly string.
    private typealias RewriteRule = (
        check: (String) -> [String]?,
        transform: ([String]) -> String
    )

    nonisolated(unsafe) private static let rewriteRules: [RewriteRule] = [
        // Swift: cannot find 'X' in scope
        (
            check: { line in
                guard line.contains("cannot find '") && line.contains("' in scope") else { return nil }
                let parts = line.components(separatedBy: "cannot find '")
                guard parts.count >= 2 else { return nil }
                let symbol = parts[1].components(separatedBy: "' in scope").first ?? ""
                let location = extractLocation(from: line)
                return [location, symbol]
            },
            transform: { parts in
                "\(parts[0]): '\(parts[1])' is undefined. Add the appropriate import or check for typos."
            }
        ),

        // Swift: has no member 'X'
        (
            check: { line in
                guard line.contains("has no member '") else { return nil }
                let parts = line.components(separatedBy: "has no member '")
                guard parts.count >= 2 else { return nil }
                let member = parts[1].components(separatedBy: "'").first ?? ""
                let location = extractLocation(from: line)
                return [location, member]
            },
            transform: { parts in
                "\(parts[0]): no member '\(parts[1])'. Check the type's API or fix the member name."
            }
        ),

        // Swift: missing return
        (
            check: { line in
                guard line.contains("missing return") else { return nil }
                return [extractLocation(from: line)]
            },
            transform: { parts in
                "\(parts[0]): missing return statement. Add a return value matching the declared return type."
            }
        ),

        // TypeScript: TS2322 type mismatch
        (
            check: { line in
                guard line.contains("TS2322") || line.contains("is not assignable to type") else { return nil }
                let location = extractLocation(from: line)
                return [location]
            },
            transform: { parts in
                "\(parts[0]): type mismatch. Check the assignment — cast, convert, or fix the upstream value."
            }
        ),

        // TypeScript: TS2304 cannot find name
        (
            check: { line in
                guard line.contains("TS2304") || (line.contains("Cannot find name") && !line.contains("in scope")) else { return nil }
                let location = extractLocation(from: line)
                return [location]
            },
            transform: { parts in
                "\(parts[0]): name not found. Check spelling or add an import statement."
            }
        ),

        // TypeScript: TS2345 argument type mismatch
        (
            check: { line in
                guard line.contains("TS2345") else { return nil }
                return [extractLocation(from: line)]
            },
            transform: { parts in
                "\(parts[0]): argument type mismatch. Check parameter types match the function signature."
            }
        ),

        // Python: SyntaxError
        (
            check: { line in
                guard line.contains("SyntaxError") else { return nil }
                return [extractLocation(from: line)]
            },
            transform: { parts in
                "\(parts[0]): syntax error. Check for unmatched brackets, missing colons, or indentation."
            }
        ),

        // Python: F401 imported but unused
        (
            check: { line in
                guard line.contains("F401") || line.contains("imported but unused") else { return nil }
                return [extractLocation(from: line)]
            },
            transform: { parts in
                "\(parts[0]): unused import. Remove it if the code that used it was deleted."
            }
        ),

        // Go: undefined
        (
            check: { line in
                guard line.contains("undefined:") else { return nil }
                return [extractLocation(from: line)]
            },
            transform: { parts in
                "\(parts[0]): undefined symbol. Check spelling or add the appropriate import."
            }
        ),

        // Rust: cannot find
        (
            check: { line in
                guard line.contains("cannot find") && line.contains("in this scope") else { return nil }
                return [extractLocation(from: line)]
            },
            transform: { parts in
                "\(parts[0]): symbol not found in scope. Add a use statement or check the module path."
            }
        ),

        // Generic: error at file:line
        (
            check: { line in
                guard line.lowercased().contains("error") else { return nil }
                let loc = extractLocation(from: line)
                guard loc != "(unknown)" else { return nil }
                return [loc, stripValidatorPrefix(line)]
            },
            transform: { parts in
                "\(parts[0]): \(parts[1])"
            }
        ),
    ]

    // MARK: - Helpers

    /// Extract file:line location from a diagnostic line.
    /// Handles formats: "file.swift:12:5: error:", "file.ts(12,5): error", "file.py:12: "
    private static func extractLocation(from line: String) -> String {
        // Pattern: filename:line or filename:line:col
        let components = line.components(separatedBy: ":")
        if components.count >= 2 {
            let file = components[0]
            let lineNum = components[1].trimmingCharacters(in: .whitespaces)
            if lineNum.allSatisfy(\.isNumber), !file.isEmpty {
                return "\(file):\(lineNum)"
            }
        }
        // Pattern: filename(line,col)
        if let parenIdx = line.firstIndex(of: "("),
           let closeIdx = line.firstIndex(of: ")"),
           parenIdx < closeIdx {
            let file = String(line[line.startIndex..<parenIdx])
            let inside = String(line[line.index(after: parenIdx)..<closeIdx])
            let lineNum = inside.components(separatedBy: ",").first ?? ""
            if lineNum.allSatisfy(\.isNumber), !file.isEmpty {
                return "\(file):\(lineNum)"
            }
        }
        return "(unknown)"
    }
}
