import Foundation

// MARK: - WorkflowSignalGenerator
//
// Phase H+2c — proposes `LearnedWorkflowPlaybook` artifacts from
// repeating ordered tool-call pairs. Heuristic: when (A, B) fires
// back-to-back within 60 s at least 3 times per session across ≥ 2
// sessions, that's a "do A then B" workflow the agent is performing
// consistently — worth codifying as a named playbook.
//
// Deterministic; no LLM. Playbook description + steps are templated
// from the observed pair. Future rounds can widen the window to
// longer sequences and richer descriptions.

public enum WorkflowSignalGenerator {

    public static func analyze(
        projectRoot: String,
        sessionId: String,
        db: SessionDatabase,
        windowSeconds: Double = 60,
        minOccurrencesPerSession: Int = 3,
        minSessions: Int = 2,
        limit: Int = 5,
        now: Date = Date()
    ) -> [LearnedWorkflowPlaybook] {
        let rows = db.workflowPairPatterns(
            projectRoot: projectRoot,
            windowSeconds: windowSeconds,
            minOccurrencesPerSession: minOccurrencesPerSession,
            minSessions: minSessions,
            limit: limit
        )
        guard !rows.isEmpty else { return [] }

        return rows.map { row in
            // Title is a stable slug of the pair — dedup by pair
            // identity across sessions.
            let title = LearnedContextDoc.sanitizeTitle(
                "\(row.firstTool)-then-\(row.secondTool)"
            )
            let description = """
            # Workflow: \(row.firstTool) → \(row.secondTool)

            The agent calls `\(row.firstTool)` immediately followed by `\(row.secondTool)` \
            repeatedly — observed \(row.totalOccurrences) times across \(row.sessionCount) \
            sessions. Codifying this pair as a playbook lets future sessions invoke the \
            sequence by name instead of re-deriving it.

            _Generated by senkani's workflow-signal detector. Extend this file with \
            project-specific invariants (common arguments, expected outputs, rollback \
            steps) — edits persist across enrichment rounds._
            """
            let steps = [
                LearnedWorkflowStep(toolName: row.firstTool,
                                    example: "senkani_\(row.firstTool) …"),
                LearnedWorkflowStep(toolName: row.secondTool,
                                    example: "senkani_\(row.secondTool) …"),
            ]
            let confidence = ConfidenceEstimator.laplace(
                avgSavedPct: 0,
                sessionCount: row.sessionCount
            )
            return LearnedWorkflowPlaybook(
                id: UUID().uuidString,
                title: title,
                description: description,
                steps: steps,
                sources: [sessionId],
                confidence: confidence,
                status: .recurring,
                createdAt: now,
                lastSeenAt: now,
                recurrenceCount: 1,
                sessionCount: row.sessionCount
            )
        }
    }
}
