#!/usr/bin/env bash
#
# generate-notices.sh — Emit THIRD-PARTY-NOTICES.md by aggregating the ACTUAL
# LICENSE text of every resolved Swift package dependency from
# `.build/checkouts/*/`. Authoritative (not a hand-maintained guess): the
# attribution + license body come straight from each dependency's own file.
#
# Surfaced by the 2026-06-08 luminary groom (decision D9, panel
# Jansen/Swyx/Dunford/Meeker): Meeker — a THIRD-PARTY-NOTICES file is REQUIRED
# before publishing the Homebrew tap. This is the buildable prep; creating the
# ckluis/homebrew-tap repo + pushing the Formula stays operator-gated.
#
# Usage:
#   tools/generate-notices.sh [output]   # default: THIRD-PARTY-NOTICES.md
# Requires `.build/checkouts` (run `swift package resolve` first).
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CHECKOUTS="$REPO_ROOT/.build/checkouts"
OUT="${1:-$REPO_ROOT/THIRD-PARTY-NOTICES.md}"

if [ ! -d "$CHECKOUTS" ]; then
  echo "error: $CHECKOUTS not found — run 'swift package resolve' first." >&2
  exit 1
fi

# Best-effort SPDX-ish label from the license text (first match wins).
detect_license() {
  local f="$1"
  if grep -qi "Apache License" "$f"; then echo "Apache-2.0"
  elif grep -qiE "^MIT License|Permission is hereby granted, free of charge" "$f"; then echo "MIT"
  elif grep -qi "BSD 3-Clause" "$f"; then echo "BSD-3-Clause"
  elif grep -qi "BSD 2-Clause" "$f"; then echo "BSD-2-Clause"
  elif grep -qi "Mozilla Public License" "$f"; then echo "MPL-2.0"
  else echo "see-text"
  fi
}

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

count=0
# Deterministic: iterate checkout dirs sorted by name.
while IFS= read -r dir; do
  name="$(basename "$dir")"
  # find the dep's license file (LICENSE, LICENSE.txt, LICENSE.md, COPYING)
  lic="$(find "$dir" -maxdepth 1 -type f \( -iname 'LICENSE' -o -iname 'LICENSE.*' -o -iname 'LICENCE' -o -iname 'LICENCE.*' -o -iname 'COPYING' -o -iname 'COPYING.*' \) 2>/dev/null | head -n1 || true)"
  [ -z "$lic" ] && continue
  spdx="$(detect_license "$lic")"
  {
    echo "## ${name}"
    echo ""
    echo "License: ${spdx}"
    echo ""
    echo '```'
    cat "$lic"
    echo '```'
    echo ""
  } >> "$tmp"
  count=$((count + 1))
done < <(find "$CHECKOUTS" -maxdepth 1 -mindepth 1 -type d | sort)

{
  echo "# Third-Party Notices"
  echo ""
  echo "senkani is distributed under its own license (see LICENSE). It bundles or"
  echo "links the following third-party Swift packages, each under its own license,"
  echo "reproduced verbatim below. Generated by \`tools/generate-notices.sh\` from the"
  echo "resolved \`.build/checkouts\` — re-run after any dependency change."
  echo ""
  echo "Components: ${count}."
  echo ""
  echo "---"
  echo ""
  cat "$tmp"
} > "$OUT"

echo "wrote ${OUT} (${count} components)"
